name: scale-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: arc-runner-set

    strategy:
      matrix:
        worker: [1,2,3,4,5]

    steps:
      - name: Test workload
        run: |
          echo "worker ${{ matrix.worker }}"
          sleep 60
